
[font]

size = 9

bold = {family = "M+1Code Nerd Font Mono", style = "Bold"}

bold_italic = {family = "M+1Code Nerd Font Mono", style = "Bold Italic"}

italic = {family = "M+1Code Nerd Font Propo", style = "Italic"}

normal = {family = "M+1Code Nerd Font Mono", style = "Regular"}

builtin_box_drawing = true
